.PHONY: docs clean docs-setup preview examples

# Default target
all: examples docs

# Build examples
examples: examples-setup
	julia --project=examples examples/make.jl

# Build specific examples (usage: make example FILTER=pattern)
example: examples-setup
	@if [ "$(FILTER)" = "" ]; then \
		echo "Error: FILTER is required. Usage: make example FILTER=pattern"; \
		exit 1; \
	fi
	julia --project=examples examples/make.jl $(FILTER)

# Build examples with local development version of RxInfer
examples-dev: examples-setup
	julia --project=examples examples/make.jl --use-dev $(if $(RXINFER),--rxinfer-path=$(RXINFER),)

# Build specific example with local development version of RxInfer
example-dev: examples-setup
	@if [ "$(FILTER)" = "" ]; then \
		echo "Error: FILTER is required. Usage: make example-dev FILTER=pattern"; \
		exit 1; \
	fi
	julia --project=examples examples/make.jl --use-dev $(if $(RXINFER),--rxinfer-path=$(RXINFER),) $(FILTER)

# Build documentation
docs: docs-setup
	julia --project=docs docs/make.jl

# Clean build artifacts
clean:
	rm -rf docs/build
	rm -rf docs/src/autogenerated
	rm -rf docs/src/categories

# Install documentation dependencies
docs-setup:
	julia --project=docs -e 'using Pkg; Pkg.instantiate()'

examples-setup:
	@echo "Note: Building examples requires Weave.jl to be installed globally."
	@echo "If not installed, run: julia -e 'using Pkg; Pkg.add(\"Weave\")'"
	@echo "Note: Example builds are cached. If you experience persistent errors, run 'make clean' first."
	julia --project=examples -e 'using Pkg; Pkg.instantiate()'

# Preview documentation in browser
preview:
	open docs/build/index.html

# Help command
help:
	@echo "Available targets:"
	@echo "  all        - Build all examples and documentation (default)"
	@echo "  examples   - Build all example notebooks"
	@echo "  example    - Build specific example (usage: make example FILTER=pattern)"
	@echo "  examples-dev - Build all examples with local RxInfer development version"
	@echo "  example-dev  - Build specific example with local RxInfer development version"
	@echo "  docs       - Build the documentation website"
	@echo "  preview    - Open documentation in browser"
	@echo "  clean      - Remove all build artifacts and caches"
	@echo ""
	@echo "Setup targets:"
	@echo "  examples-setup - Install examples dependencies"
	@echo "  docs-setup    - Install documentation dependencies"
	@echo ""
	@echo "Requirements:"
	@echo "  Weave.jl must be installed globally for examples to build."
	@echo "  Install with: julia -e 'using Pkg; Pkg.add(\"Weave\")'"
	@echo "  Example builds are cached by default. If you fix an example but still see errors,"
	@echo "  run 'make clean' to clear the cache before rebuilding."
	@echo ""
	@echo "Examples:"
	@echo "  make example FILTER=LinearRegression  # Build specific example"
	@echo "  make example-dev FILTER=LinearRegression  # Build with local RxInfer"
	@echo "  make example-dev FILTER=LinearRegression RXINFER=/path/to/RxInfer.jl  # Build with specific RxInfer"
	@echo "  make clean && make all               # Clean build everything"
	@echo "  make docs && make preview            # Build and view docs"
