.PHONY: docs clean docs-setup preview examples

# Default target
all: examples docs

# Build examples
examples: examples-setup
	julia --project=examples examples/make.jl

# Build specific examples (usage: make example FILTER=pattern)
example: examples-setup
	@if [ "$(FILTER)" = "" ]; then \
		echo "Error: FILTER is required. Usage: make example FILTER=pattern"; \
		exit 1; \
	fi
	julia --project=examples examples/make.jl $(FILTER)

# Build documentation
docs: docs-setup
	julia --project=docs docs/make.jl

# Clean build artifacts
clean:
	rm -rf docs/build
	rm -rf docs/src/examples
	rm -rf docs/src/autogenerated

# Install documentation dependencies
docs-setup:
	julia --project=docs -e 'using Pkg; Pkg.instantiate()'

examples-setup:
	julia --project=examples -e 'using Pkg; Pkg.instantiate()'

# Preview documentation in browser
preview:
	open docs/build/index.html

# Help command
help:
	@echo "Available targets:"
	@echo "  all        - Build all examples and documentation (default)"
	@echo "  examples   - Build all example notebooks"
	@echo "  example    - Build specific example (usage: make example FILTER=pattern)"
	@echo "  docs       - Build the documentation website"
	@echo "  preview    - Open documentation in browser"
	@echo "  clean      - Remove all build artifacts and caches"
	@echo ""
	@echo "Setup targets:"
	@echo "  examples-setup - Install examples dependencies"
	@echo "  docs-setup    - Install documentation dependencies"
	@echo ""
	@echo "Examples:"
	@echo "  make example FILTER=LinearRegression  # Build specific example"
	@echo "  make clean && make all               # Clean build everything"
	@echo "  make docs && make preview            # Build and view docs"
